final Map<String, String> enUS = {
  "Offline": "Offline",
  "New Customer Address": "New Customer Address",
  "Enter your customer address": "Enter your customer address",
  "Search for a customer": "Search for a customer",
  "Search": "Search",
  "Dashboard": "Dashboard",
  "Orders": "Orders",
  "Logout": "Logout",
  "Customer address": "Customer address",
  "Continue": "Continue",
  "Delivery Address": "Delivery Address",
  "Customer delivery details": "Customer delivery details",
  "Recipient Name": "Recipient Name",
  "Enter recipient name": "Enter recipient name",
  "Enter recipient building number": "Enter recipient building number",
  "Phone Number": "Phone Number",
  "Item Information": "Item Information",
  "Enter Total amount": "Enter Total amount",
  "Item Description": "Item Description",
  "Enter items description": "Enter items description",
  "Delivery note(Optional)": "Delivery note(Optional)",
  "Leave a note": "Leave a note",
  "Where should the order be left?(optional)": "Where should the order be left?(optional)",
  "Select Option": "Select Option",
  "Collect bill/check from customer": "Collect bill/check from customer",
  "Collect courier fee from customer": "Collect courier fee from customer",
  "Request order": "Request order",
  "Delivery pending": "Delivery pending",
  "Delivered": "Delivered",
  "Select option": "Select option",
  "Click if courier should collect invoice amount from customer":
      "Click if courier should collect invoice amount from customer",
  "Uncheck if courier should not collect courier fee from customer":
      "Uncheck if courier should not collect courier fee from customer",
  "Enter your comment": "Enter your comment",
  "comment": "comment",
  "comment to courier": "comment to courier",
  "Drop at the door": "Drop at the door",
  "Call me when you arrive": "Call me when you arrive",
  "Hand it to me": "Hand it to me",
  "Others": "Others",
  'No orders completed': 'No orders completed',
  "Waiting orders": "Waiting orders",
  "No orders yet": "No orders yet",
  "No orders": "No orders",
  'Settings': 'Settings',
  'Business Time': 'Business Time',
  'Comment management': 'Comment management',
  'Opening - Closing Time': 'Opening - Closing Time',
  'Update time': 'Update time',
  'Comments': 'Comments',
  'No comments': 'No comments',
  'Order Details': 'Order Details',
  'Order # ': 'Order # ',
  'Date:': 'Date:',
  'ORDER SUMMARY': 'ORDER SUMMARY',
  'Discount': 'Discount',
  'Delivery Fee': 'Delivery Fee',
  'Total': 'Total',
  'ORDER NOTE': 'ORDER NOTE',
  'No Orders Yet': 'No Orders Yet',
  'Accepted': 'Accepted',
  'Rejected': 'Rejected',
  'Pending': '',
  'Accept': 'Accept',
  'Reject': 'Reject',
  'CUSTOMER DETAILS': 'Customer Details',
  'Delivered to customer': 'Delivered to customer',
  'COURIER DETAILS': 'COURIER DETAILS',
  'Courier Name': 'Courier Name',
  'Online Orders': 'Online Orders',
  'Completed': 'Completed',
  'Offline Orders': 'Offline Orders',
  'Estimated arrival': 'Estimated arrival',
  'status': 'status',
  'Subtotal': 'Subtotal',
  'No Orders Completed': 'No Orders Completed',
  'Offline Food Delivery': 'Offline Food Delivery',
  'Restaurant Address': 'Restaurant Address',
  'Customer Address': 'Customer Address',
  'Delivery cost': 'Delivery cost',
  'Time:': 'Time:',
  'Name:  ': 'Name:  ',
  'Not set': 'Not set',
  'Type:  ': 'Type:  ',
  'Delivery': 'Delivery',
  'Distance': 'Distance',
  'Total Amount': 'Total Amount',
  'Back': 'Back',
  'Offline details screen': 'Offline details screen',
  'Offline Delivery': 'Offline Delivery',
  'Recipient name': 'Recipient name',
  'Recipient apartment/floor/office number (optional)': '',
  'Please enter your phone number': 'Please enter your phone number',
  'Phone number': 'Phone number',
  'Item information': 'Item information',
  'Enter total amount': 'Enter total amount',
  'Amount': 'Amount',
  'Enter item description': 'Enter item description',
  'Item description': 'Item description',
  'Enter delivery note': 'Enter delivery note',
  'Delivery note': 'Delivery note',
  'By clicking this box, you agree that the courier should collect cash':
      'By clicking this box, you agree that the courier should collect cash',
  'Please fill all required fields': 'Please fill all required fields',
  'Incomplete fields': 'Incomplete fields',
  'Failed to create order, try again': 'Failed to create order, try again',
  'Request Order': 'Request Order',
  'Customer Details': '',
  'Customer Name': 'Customer Name',
  'Customer Phone Number': 'Customer Phone Number',
  'Apartment/Block/Room number': 'Apartment/Block/Room number',
  'Delivery Note': 'Delivery Note',
  'Item Details': 'Item Details',
  'Item amount': 'Item amount',
  'Payment Details': 'Payment Details',
  'Payment Mode': 'Payment Mode',
  'cash': 'cash',
  'Should courier collect money from customer?': 'Should courier collect money from customer?',
  'Place order': 'Place order',
  'Request now': 'Request now',
  'Reports': 'Reports',
  'No Sales Made Yet': 'No Sales Made Yet',
  'Ranked by Order Volume': 'Ranked by Order Volume',
  'Top-Selling Items': 'Top-Selling Items',
  'Payouts': 'Payouts',
  'Offline Ordering': 'Offline Ordering',
  'Admin': 'Admin',
  'New orders': 'New orders',
  'Tap anywhere to view them': 'Tap anywhere to view them',
  'Current payout balance': 'Current payout balance',
  'Only credit card transactions': 'Only credit card transactions',
  'Login': 'Login',
  'Email Address': 'Email Address',
  'Password': 'Password',
  'Create account': 'Create account',
  'Get Directions?': 'Get Directions?',
  'Balances': "Balances",
  'Revenue': "Revenue",
  'Net': "Net",
  "go offline": "go offline",
  "GO ONLINE": "GO ONLINE",
  "Error": "Error",
  "Yes": "Yes",
  "No": "No",
  "Place Order": "Place Order",
  "Please input customer address": "Please input customer address"
};
