final Map<String, String> es = {
  "Offline": "Offline",
  "New Customer Address": "Uus kliendiaadress",
  "Enter your customer address": "Sisestage oma kliendiaadress",
  "Search for a customer": "Otsige klienti",
  "Search": "Otsing",
  "Dashboard": "Armatuurlaud",
  "Orders": "Tellimused",
  "Logout": "Logi välja",
  "Customer address": "Kliendi aadress",
  "Continue": "Jätka",
  "Delivery Address": "Saaja aadress",
  "Customer delivery details": "Kliendi kohaletoimetamise üksikasjad",
  "Recipient Name": "Saaja nimi",
  "Enter recipient name": "	Sisestage adressaadi nimi",
  "Enter recipient building number": "Sisestage adressaadi hoone number",
  "Phone Number": "Telefoninumber",
  "Item Information": "Üksuse teave",
  "Enter Total amount": "Sisestage kogusumma",
  "Item Description": "Toote kirjeldus",
  "Enter items description": "Sisestage üksuste kirjeldus",
  "Delivery note(Optional)": "Saatekiri (valikuline)",
  "Leave a note": "Jäta märge",
  "Where should the order be left?(optional)": "Kuhu tellimus jätta? (Valikuline)",
  "Select Option": "Valige Valik",
  "Collect bill/check from customer": "Koguge arve/tšekk kliendilt",
  "Collect courier fee from customer": "Koguge kliendilt kullertasu",
  "Request order": "Taotle tellimust",
  "Delivery pending": "Tarne ootel",
  "Delivered": "Kohale toimetatud",
  "Select option": "Valige suvand",
  "Click if courier should collect invoice amount from customer":
      "Klõpsake, kas kuller peaks arve summa kliendilt koguma",
  "Uncheck if courier should not collect courier fee from customer":
      "Tühjendage märkeruut, kas kuller ei peaks kliendilt kullertasu sisse nõudma",
  "Enter your comment": "Sisestage oma kommentaar",
  "comment": "kommentaar",
  "comment to courier": "kommenteerige kullerile",
  "Drop at the door": "Langetage uksele",
  "Call me when you arrive": "Helistage mulle, kui jõuate",
  "Hand it to me": "Andke see mulle",
  "Others": "Teised",
  'No orders completed': 'Tellimusi pole lõpetatud',
  "Waiting orders": "Tellimuste ootamine",
  "No orders yet": "Tellimusi veel pole",
  "No orders": "Tellimusi pole",
  'Settings': "Seaded",
  'Business Time': 'Äriaeg',
  'Comment management': 'Kommentaaride haldamine',
  'Opening - Closing Time': 'Avamine - sulgemisaeg',
  'Update time': 'Värskendamise aeg',
  'Comments': 'Kommentaarid',
  'No comments': 'Kommentaarid puuduvad',
  'Order Details': 'Tellimuse üksikasjad',
  'Order # ': 'Tellimus #',
  'Date:': 'Kuupäev:',
  'ORDER SUMMARY': 'TELLIMUSTE KOKKUVÕTE',
  'Discount': 'Soodustus',
  'Delivery Fee': 'Kohaletoimetamise tasu',
  'Total': 'Kokku',
  'ORDER NOTE': 'TELLI MÄRKUS',
  'No Orders Yet': 'Tellimusi veel pole',
  'Accepted': 'Vastu võetud',
  'Rejected': 'Tagasilükatud',
  'Pending': 'Ootel',
  'Accept': 'Nõustu',
  'Reject': 'Keeldu',
  'CUSTOMER DETAILS': 'KLIENDI ÜKSIKASJAD',
  'Delivered to customer': 'Tarnitakse kliendile',
  'COURIER DETAILS': 'KULJERI ÜKSIKASJAD',
  'Courier Name': 'Kulleri nimi',
  'Online Orders': 'Interneti -tellimused',
  'Completed': 'Lõpetatud',
  'Offline Orders': 'Võrguühenduseta tellimused',
  'Estimated arrival': 'Hinnanguline saabumine',
  'status': 'staatus',
  'Subtotal': 'Vahesumma',
  'No Orders Completed': 'Ükski tellimus pole lõpetatud',
  'Offline Food Delivery': 'Toidu kohaletoimetamine võrguühenduseta',
  'Customer Address': 'Kliendi aadress',
  'Delivery cost': 'Kohaletoimetamise maksumus',
  'Time:': 'Aeg:',
  'Name:  ': 'Nimi:',
  'Not set': 'Pole määratud',
  'Type:  ': 'Tüüp:',
  'Delivery': 'Kohaletoimetamine',
  'Distance': 'Kaugus',
  'Total Amount': 'Kogu summa',
  'Back': 'tagasi',
  'Offline details screen': 'Võrguühenduseta üksikasjade ekraan',
  'Offline Delivery': 'Võrguühenduseta kohaletoimetamine',
  'Recipient name': 'Saaja nimi',
  'Recipient apartment/floor/office number (optional)':
      'Saaja korteri/korruse/kontori number (valikuline)',
  'Please enter your phone number': 'Palun sisestage oma telefoninumber',
  'Phone number': 'Telefoninumber',
  'Item information': 'Üksuse teave',
  'Enter total amount': 'Sisestage kogusumma',
  'Amount': 'Kogus',
  'Enter item description': 'Sisestage üksuse kirjeldus',
  'Item description': 'Toote kirjeldus',
  'Enter delivery note': 'Sisestage saateleht',
  'By clicking this box, you agree that the courier should collect cash':
      'Sellel kastil klõpsates nõustute, et kuller peab sularaha sisse võtma',
  'Please fill all required fields': 'Palun täitke kõik kohustuslikud väljad',
  'Incomplete fields': 'Mittetäielikud väljad',
  'Failed to create order, try again': 'Tellimuse loomine ebaõnnestus, proovige uuesti',
  'Request Order': 'Taotle tellimust',
  'Customer Details': 'Kliendi andmed',
  'Customer Name': 'Kliendi nimi',
  'Customer Phone Number': 'Kliendi telefoninumber',
  'Apartment/Block/Room number': 'Korteri/korteri/toa number',
  'Delivery Note': 'Saatekiri',
  'Item Details': 'Üksuse üksikasjad',
  'Item amount': 'Kauba summa',
  'Payment Details': 'Makse andmed',
  'Payment Mode': 'Makse režiim',
  'cash': 'sularaha',
  'Should courier collect money from customer?': 'Kas kuller peaks kliendilt raha koguma?',
  'Place order': 'Esita tellimus',
  'Request now': 'Taotlege kohe',
  'Reports': 'Aruanded',
  'No Sales Made Yet': 'Müüki pole veel tehtud',
  'Ranked by Order Volume': 'Järjestatud tellimuste mahu järgi',
  'Top-Selling Items': 'Enimmüüdud esemed',
  'Payouts': 'Väljamaksed',
  'Offline Ordering': 'Võrguühenduseta tellimine',
  'Admin': 'Administraator',
  'New orders': 'Uued tellimused',
  'Tap anywhere to view them': 'Nende vaatamiseks puudutage suvalist kohta',
  'Current payout balance': 'Praegune väljamakse saldo',
  'Only credit card transactions': 'Ainult krediitkaarditehingud',
  'Login': 'Logi sisse',
  'Email Address': 'E-posti aadress',
  'Password': 'Parool',
  'Create account': 'Loo konto',
  'Get Directions?': 'Juhiseid saama?',
  'Balances': "Tasakaalud",
  'Revenue': "Tulu",
  'Net': "Net",
  "go offline": "võrguühenduseta minema",
  "GO ONLINE": "LÄHE ONLINE",
  "Restaurant Address": "Restorani aadress",
  "Error": "Viga",
  "Yes": "Jah",
  "No": "Ei",
  "Place Order": "Esita tellimus",
  "Please input customer address": "Palun sisestage kliendi aadress"
};
