final Map<String, String> ru = {
  "Offline": "Офлайн",
  "New Customer Address": "Новый адрес клиента",
  "Enter your customer address": "Введите адрес вашего клиента",
  "Search for a customer": "Поиск Клиента",
  "Search": "Поиск",
  "Dashboard": "Панель управления",
  "Orders": "Заказы",
  "Logout": "Выйти",
  "Customer address": "Адрес клиента",
  "Continue": "Продолжить",
  "Delivery Address": "Адрес доставки",
  "Customer delivery details": "Детали доставки клиенту",
  "Recipient Name": "Имя получателя",
  "Enter recipient name": "Введите имя получателя",
  "Enter recipient building number": "Введите номер здания получателя",
  "Phone Number": "Телефонный номер",
  "Item Information": "Информация о товаре",
  "Enter Total amount": "Введите общую сумму",
  "Item Description": "Описание заказа",
  "Enter items description": "Введите описание заказа",
  "Delivery note(Optional)": "Транспортная накладная (необязательно)",
  "Leave a note": "Оставить примечание",
  "Where should the order be left?(optional)": "Где оставить заказ? (Необязательно)",
  "Select Option": "Выберите опцию",
  "Collect bill/check from customer": "Получение счета / чека от клиента",
  "Collect courier fee from customer": "Получение курьерского сбора с клиента",
  "Request order": "Порядок запроса",
  "Delivery pending": "Ожидается доставка",
  "Delivered": "toimetatud	Доставлено",
  "Select option": "Выберите опцию",
  "Click if courier should collect invoice amount from customer":
      "Нажмите, если курьер должен забрать сумму счета от клиента",
  "Uncheck if courier should not collect courier fee from customer":
      "Снимите флажок, если курьер не должен взимать с клиента плату за курьерскую доставку.",
  "Enter your comment": "Введите свой комментарий",
  "comment": "комментарий",
  "comment to courier": "комментарий курьеру",
  "Drop at the door": "Оставить у двериr",
  "Call me when you arrive": "Позвони мне, когда приедешь",
  "Hand it to me": "Передай это мне",
  "Others": "Другие",
  'No orders completed': 'Нет выполненных заказов',
  "Waiting orders": "Ожидание заказов",
  "No orders yet": "Пока нет заказов",
  "No orders": "нет заказов",
  'Settings': "Настройки",
  'Business Time': 'Рабочее время',
  'Comment management': 'Управление комментариями',
  'Opening - Closing Time': 'Открытие - Время закрытия',
  'Update time': 'Время обновления',
  'Comments': 'Комментарии',
  'No comments': 'Без комментариев',
  'Order Details': 'Информация для заказа',
  'Order # ': 'Заказ #',
  'Date:': 'Дата:',
  'ORDER SUMMARY': 'ИТОГ ЗАКАЗА',
  'Discount': 'Скидка',
  'Delivery Fee': 'Плата за доставку',
  'Total': 'Всего',
  'ORDER NOTE': 'ПРИМЕЧАНИЕ ДЛЯ ЗАКАЗА',
  'No Orders Yet': 'Заказов пока нет',
  'Accepted': 'Принято',
  'Rejected': 'Отклоненный',
  'Pending': 'В ожидании',
  'Accept': 'Принять',
  'Reject': 'Отклонить',
  'CUSTOMER DETAILS': 'ДЕТАЛИ КЛИЕНТА',
  'Delivered to customer': 'Доставлено заказчику',
  'COURIER DETAILS': 'ДЕТАЛИ КУРЬЕРА',
  'Courier Name': 'Имя курьера',
  'Online Orders': 'Онлайн-заказы',
  'Completed': 'Завершенo',
  'Offline Orders': 'Офлайн-заказы',
  'Estimated arrival': 'Ожидаемое прибытие',
  'status': 'статус',
  'Subtotal': 'Промежуточный итог',
  'No Orders Completed': 'Заказы не выполнены',
  'Offline Food Delivery': 'Офлайн-доставка еды',
  'Restaurant Address': 'Адрес ресторана',
  'Customer Address': 'Адрес клиента',
  'Delivery cost': 'Стоимость доставки',
  'Time:': 'Время:',
  'Name:  ': 'Имя:',
  'Not set': 'Не установлено',
  'Type:  ': 'Тип:',
  'Delivery': 'Доставка',
  'Distance': 'Расстояние',
  'Total Amount': 'Итого',
  'Back': 'Назад',
  'Offline details screen': 'Экран сведений оффлайн',
  'Offline Delivery': 'Офлайн-доставка',
  'Recipient name': 'Имя получателя',
  'Recipient apartment/floor/office number (optional)':
      'Номер квартиры / этажа / офиса получателя (необязательно)',
  'Please enter your phone number': 'Пожалуйста введите ваш номер телефона',
  'Phone number': 'Телефонный номер',
  'Item information': 'Информация о товаре',
  'Enter total amount': 'Введите общую сумму',
  'Amount': 'Количество',
  'Enter item description': 'Количество',
  'Item description': 'Введите описание товара',
  'Enter delivery note': 'Описание товара',
  'Delivery note': 'Накладная',
  'By clicking this box, you agree that the courier should collect cash':
      'Установив это поле, вы соглашаетесь с тем, что курьер должен забрать наличные.',
  'Please fill all required fields': 'Пожалуйста, заполните все обязательные поля',
  'Incomplete fields': 'Неполные поля',
  'Failed to create order, try again': 'Не удалось создать заказ, попробуйте еще раз',
  'Request Order': 'Порядок запроса',
  'Customer Details': 'Подробная информация о клиенте',
  'Customer Name': 'Имя покупателя',
  'Customer Phone Number': 'Номер телефона клиента',
  'Apartment/Block/Room number': 'Квартира / Блок / Номер квартиры',
  'Delivery Note': 'Накладная',
  'Item Details': 'Детали предмета',
  'Item amount': 'Количество товара',
  'Payment Details': 'Детали оплаты',
  'Payment Mode': 'Режим оплаты',
  'cash': 'наличные',
  'Should courier collect money from customer?': 'Должен ли курьер собирать деньги с клиента?',
  'Place order': 'Разместить заказ',
  'Request now': 'Запросить сейчас',
  'Reports': 'Заказы',
  'No Sales Made Yet': 'Продаж еще не осуществлено',
  'Ranked by Order Volume': 'Рейтинг по объему заказа',
  'Top-Selling Items': 'Самые продаваемые товары',
  'Payouts': 'Выплаты',
  'Offline Ordering': 'Офлайн-заказ',
  'Admin': 'Админ',
  'New orders': 'Новые заказы',
  'Tap anywhere to view them': 'Нажмите в любом месте, чтобы просмотреть их',
  'Current payout balance': 'Текущий баланс выплат',
  'Only credit card transactions': 'Только транзакции по кредитной карте',
  'Login': 'Авторизоваться',
  'Email Address': 'Адрес электронной почты',
  'Password': 'Пароль',
  'Create account': 'создать учетную запись',
  'Get Directions?': 'Получить направление?',
  'Balances': 'Остатки',
  'Revenue': "Доход",
  'Net': "Сеть",
  "go offline": "перейти в автономный режим",
  "GO ONLINE": "ВЫЙТИ В ОНЛАЙН",
  "Error": "Ошибка",
  "Yes": "да",
  "No": "Нет",
  "Place Order": "Разместить заказ",
  "Please input customer address": "Пожалуйста, введите адрес клиента",
};
